export const listFakeData = [
    {
        id: 0,
        name: 'Nazov',
        statusDone: true,
    },
    {
        id: 1,
        name: 'Zoznam 2',
        statusDone: false,
    },
    {
        id: 2,
        name: 'Zoznam 3',
        statusDone: true,
    },
    {
        id: 3,
        name: 'Zoznam 4',
        statusDone: true,
    },
];

const DATA = [
    {
        id: '1',
        time: '16:10',
        systolicPressure: '120',
        diastolicPressure: '80',
        sf: '12',
        df: '10',
        do: '20',
        pulse: '60',
        comment: 'test',
    },
    {
        id: '2',
        time: '15:30',
        systolicPressure: '120',
        diastolicPressure: '80',
        sf: '12',
        df: '10',
        do: '20',
        pulse: '60',
        comment: 'test',
    },
    {
        id: '3',
        time: '10:30',
        systolicPressure: '120',
        diastolicPressure: '80',
        sf: '12',
        df: '10',
        do: '20',
        pulse: '60',
        comment: 'test',
    },
    {
        id: '7',
        time: '10:30',
        systolicPressure: '120',
        diastolicPressure: '80',
        sf: '12',
        df: '10',
        do: '20',
        pulse: '60',
        comment: 'test',
    },
    {
        id: '4',
        time: '10:30',
        systolicPressure: '120',
        diastolicPressure: '80',
        sf: '12',
        df: '10',
        do: '20',
        pulse: '60',
        comment: 'test',
    },
    {
        id: '5',
        time: '10:30',
        systolicPressure: '120',
        diastolicPressure: '80',
        sf: '12',
        df: '10',
        do: '20',
        pulse: '60',
        comment: 'test',
    },
    {
        id: '6',
        time: '10:30',
        systolicPressure: '120',
        diastolicPressure: '80',
        sf: '12',
        df: '10',
        do: '20',
        pulse: '60',
        comment: 'test',
    },
];
